export const IT_DATA_COURSES = {
    title: "IT và phần mềm",
    type: "course",
    arrayData: [
      {
        id: 1,
        thumbnail: "/courses/it-1.png",
        courseTitle: "Lập trình Python cơ bản",
        author: "Đăng Nguyễn, Nhật Trường",
        rate: 4,
        numberOfRates: 899,
        price: 380,
      },
      {
        id: 2,
        thumbnail: "/courses/it-2.png",
        courseTitle: "Thiết kế và phát triển website",
        author: "Phạm Thế Anh",
        rate: 4,
        numberOfRates: 1242,
        price: 250,
      },
      {
        id: 3,
        thumbnail: "/courses/it-3.png",
        courseTitle: "An toàn thông tin và bảo mật mạng",
        author: "Nguyễn Ngọc Quang",
        rate: 4,
        numberOfRates: 678,
        price: 270,
      },
      {
        id: 4,
        thumbnail: "/courses/it-4.png",
        courseTitle: "Blockchain và các ứng dụng trên nền tảng này",
        author: "Tuấn Võ Phạm",
        rate: 4,
        numberOfRates: 2138,
        price: 400,
      },
      {
        id: 5,
        thumbnail: "/courses/it-1.png",
        courseTitle: "Lập trình Python cơ bản",
        author: "Đăng Nguyễn, Nhật Trường",
        rate: 4,
        numberOfRates: 899,
        price: 380,
      },
    ],
  };